Upgrade embulk 0.8+
civitaspo/embulk-filter-join_file pull request #3
Opened 2017-06-17 12:29 UTC by takasick

It seems that it does not work now when input contains json type column. I found that it works as long as embulk 0.8 or higher, so I tried to deal with it.
Would you merge this change?

2017-06-19 13:43 UTC, civitaspo commented
Thanx a lot. I will release a new version later.

2017-06-19 16:04 UTC, civitaspo requested changes
Please change a bit more!

2017-06-19 16:04 UTC, civitaspo commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-2.6-all.zip
Latest gradle version Embulk uses is `gradle-3.2.1-bin.zip`, so update this.

2017-06-19 16:04 UTC, civitaspo commented on src/main/java/org/embulk/filter/join_file/FilteredPageOutput.java
> +            else if (Types.JSON.equals(inputColumn.getType())) {
Could you divide the p-r to Upgrading 0.8.x and Supporting JSON? This is because supporting JSON has more changes and discussions.

2017-06-20 15:36 UTC, takasick commented
Thank you for considering my request.

I updated gradle, revert undiscussed JSON support code and pushed.

For JSON column support, should I create a issue?

2017-06-21 00:10 UTC, civitaspo commented
Good.

> For JSON column support, should I create a issue?

Ok, I follow up later. Wait for a while.

2017-06-21 00:10 UTC, civitaspo approved these changes

2017-06-21 00:10 UTC, merged